'use strict';

let start = document.getElementById('start'),
    budgetValue = document.getElementsByClassName('budget-value')[0],
    dayBudgetValue = document.getElementsByClassName('.daybudget-value')[0],
    levelValue = document.getElementsByClassName('.level-value')[0],
    expensesValue = document.getElementsByClassName('.expenses-value')[0],
    optionalExpensesValue = document.getElementsByClassName('.optionalexpenses-value')[0],
    incomeValue = document.getElementsByClassName('.income-value')[0],
    monthSavingsValue = document.getElementsByClassName('.monthsavings-value')[0],
    yearsSavingsValue = document.getElementsByClassName('.yearsavings-value')[0],
    expensesItem = document.getElementsByClassName('expenses-item'),
    approveExpenses = document.getElementsByTagName('button')[0],
    approveOptionalExpenses = document.getElementsByTagName('button')[1],
    calculateBudget = document.getElementsByTagName('button')[2],
    optionalExpenses = document.querySelectorAll('.optionalexpenses-item'),
    chooseIncome = document.querySelector('.choose-income'),
    savings = document.querySelector('#savings'),
    chooseSum = document.querySelector('.choose-sum'),
    choosePercent = document.querySelector('.choose-percent'),
    year = document.querySelector('.year-value'),
    month = document.querySelector('.month-value'),
    day = document.querySelector('.day-value');
